language: python
python:
    #- "3.3" test stops at installing spyder notebook etc
    - "3.4"
    - "3.5"
    - "3.6"

install: "python setup.py install"
before_script: cd test
script:
    - python run_tests.py
notifications:
    email:
        recipients:
            - ben.bob@gmail.com
        on_success: never
        on_failure: always
